version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image:
  - Ubuntu1804
  - Visual Studio 2017
clone_depth: 1
stack: jdk 11,docker
build_script:
  - ./gradlew gradleHome downloadDependencies --parallel --refresh-dependencies --stacktrace --build-cache --configure-on-demand --no-daemon 
  - ./gradlew build -x test -x javadoc -x check --parallel --stacktrace --build-cache --configure-on-demand --no-daemon
