exclude:
  - .idea
  - .sass-cache
  - .history
  - .jekyll-cache
  - .jekyll-metadata
  - developer
  - 4.*
  - 5.*
  - 6.*
  - 7.*
  - 8.*
  - 9.*
  - 10.*
  - 11.*
  - 12.*
  - 13.*
  - 14.*
  - 15.*
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-include-cache
relative_links:
  enabled:     true
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1